### ISSUE TITLE
Google Calendar error

### ISSUE THREAD

**Issue by vminfra** [futurice/meeting-room-tablet#25]
It is always showing error dialog box

Google Calendar error

No meetings room calendars found. Please ensure that a Google Account has been configured on this device and that google calendar has been set to sync the meeting room calendars.

Please help me ....

I have already given one mail id and synced it with google calendar.

**Comment by Wisheri** [comment]
Hi!

I'll try to help you the best I can :)

The error that you are seeing is displayed either when you don't have a Google account synced correctly with the tablet or because you don't have any resource calendars synced with the Google account.

Can you first check that the account is synced correctly with the tablet?

If it is, do you have any calendar resources synced with the account? You can find help for creating a calendar for a room or shared space [here](https://support.google.com/calendar/answer/44105?hl=en&rd=1)

**Comment by jasGD** [comment]
Hi - i have the same problem and I guess the solution but I want to be sure: are you using the display with an "Google Apps for Work" resource calendar? I only have a private google calendar - so I guess thats my and propably also vminfra´s problem. if so - could the app be tweaked that it also accepts normal calendar?

**Comment by troyxmccall** [comment]
I have the same issue, using "Google apps for work". I've tried multiple accounts with shared calendars.

**Comment by Wisheri** [comment]
Yes, this application in fact requires Google apps for work or Google apps for education since it uses resource calendars for the rooms. This should probably be highlighted even more in the documentation.

Currently there are no plans to make it work for normal calendars, since this application is meant for business use. However, we don't mind if someone wants to implement this feature and include it in the application. This just isn't a priority for us at the moment.

@troyxmccall Do you have resource calendars synced with the account or just regular Google calendars?

**Comment by troyxmccall** [comment]
Ah, I have the legacy addition of Google apps for Work. 

https://support.google.com/a/answer/60766?hl=en

**Comment by pedpess** [comment]
Issue solved with PR #44

**Comment by pedpess** [comment]
Issue solved with PR #44
