### ISSUE TITLE
Incorrect name showing when reserving from web

### ISSUE THREAD

**Issue by bholdman** [futurice/meeting-room-tablet#37]
When a room is reserved through the web interface for the Google calendar it is showing the email address of the resource/calendar instead of the name of the event.

mydomain_2d3436333337393433353632@resource.calendar.google.com

On the web version of the calendar a reservator reservation and a "regular" web reservation look the same with all information being correct.

**Comment by Wisheri** [comment]
Thanks @bholdman for reporting this bug. This was accidentally passed on the latest release. I made a quick fix that now shows "Reserved" instead of the address of the resource calendar.

We removed showing the meeting titles for confidentiality reasons as confidential meeting names where shown in public at our office. We are now working on making this configurable in the application. Hopefully we'll get the new version out already by the end of this week.
